### ISSUE TITLE
[Feature] : Add Navbar and Footer for better Navigation of website

### ISSUE THREAD

**Issue by Adi-204** [metakgp/travel-buddy#7]

**Comment by saharsh-agrawal** [comment]
The header and footer are somewhat unnecessary in this project, especially when explicit buttons are given on every page for every possible page they might want to change to.

For example, this one looks a bit forced and squeezed in here. You can work on the colours, responsiveness, content (items), and most importantly, its responsiveness in various device sizes and ratios.

Moreover, since, this is an open-source community project, the footer content will not contain any copyright information and might instead link to the Github Repo or a contact number/email may be.
